### ISSUE TITLE
update react-router to avoid warning

### ISSUE THREAD

**Issue by chenkang084** [cobish/cobish.github.io#29]
pls update react-router to **3.0.5** to avoid below warning in console.

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

> Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by cobish** [comment]
@chenkang084 Thanks a lot.

**Comment by cobish** [comment]
@chenkang084 Is there no warning now?

**Comment by chenkang084** [comment]
no .it runs well.
